set(VCPKG_CMAKE_SYSTEM_VERSION 6.1)
set(VCPKG_TARGET_ARCHITECTURE x64)

set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)

if("${PORT}" MATCHES "^(gtest.*|tbb.*)")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()

set(VCPKG_C_FLAGS "/DBOOST_USE_WINAPI_VERSION=BOOST_WINAPI_VERSION_WIN7")
set(VCPKG_CXX_FLAGS "${VCPKG_C_FLAGS}")

if(NOT "${PORT}" MATCHES "^(boost.*)")
    cmake_path(GET CMAKE_CURRENT_LIST_FILE FILENAME TOOLCHAIN_FILENAME)
    set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/../Toolchains/${TOOLCHAIN_FILENAME}")
    set(VCPKG_LOAD_VCVARS_ENV ON)

    if(DEFINED VCPKG_PLATFORM_TOOLSET)
        set(VCPKG_PLATFORM_TOOLSET ClangCL)
    endif()

    set(VCPKG_ENV_PASSTHROUGH_UNTRACKED "LLVMInstallDir;LLVMToolsVersion")
endif()
